version: "3.9"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitness
    container_name: fitness
    restart: unless-stopped
    env_file: .env
    environment:
      - SESSION_SECRET=$SESSION_SECRET
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
      - STRAVA_CALLBACK_URL=$STRAVA_CALLBACK_URL
    ports:
      - "8080:80"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: npm run start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: